slug: ffcws
visit: timepoint
charts:
- chart: cm1bsex
  title: Sex
- chart: ck6ethrace
  title: Race

webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org

